### ISSUE TITLE
failure at 'npm run webpack' on OSX and Centos

### ISSUE THREAD

**Issue by joncourt** [kafka-lens/kafka-lens#57]
I've fought my way through installing and upgrading npm from https://github.com/npm/npm/issues/15821 but now i'm getting the following issue running webpack.  Not being skilled in npm or webpack i'm not sure how to fix this... any suggestions are welcome please?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'webpack' ]
2 info using npm@6.9.0
3 info using node@v6.16.0
4 verbose run-script [ 'prewebpack', 'webpack', 'postwebpack' ]
5 info lifecycle kafka-lens@0.1.0~prewebpack: kafka-lens@0.1.0
6 info lifecycle kafka-lens@0.1.0~webpack: kafka-lens@0.1.0
7 verbose lifecycle kafka-lens@0.1.0~webpack: unsafe-perm in lifecycle true
8 verbose lifecycle kafka-lens@0.1.0~webpack: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/kafka-lens/node_modules/.bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle kafka-lens@0.1.0~webpack: CWD: /root/kafka-lens
10 silly lifecycle kafka-lens@0.1.0~webpack: Args: [ '-c', 'webpack' ]
11 silly lifecycle kafka-lens@0.1.0~webpack: Returned: code: 2  signal: null
12 info lifecycle kafka-lens@0.1.0~webpack: Failed to exec webpack script
13 verbose stack Error: kafka-lens@0.1.0 webpack: `webpack`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid kafka-lens@0.1.0
15 verbose cwd /root/kafka-lens
16 verbose Linux 3.10.0-862.3.2.el7.x86_64
17 verbose argv "/usr/bin/node" "/bin/npm" "run" "webpack"
18 verbose node v6.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error kafka-lens@0.1.0 webpack: `webpack`
22 error Exit status 2
23 error Failed at the kafka-lens@0.1.0 webpack script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by howardNa** [comment]
Hey @joncourt are you running windows?

**Comment by howardNa** [comment]
@joncourt 

Hey Jon,
Follow these exact steps and let me know what you get so I can help you out further.
1. Delete your node_modules folders + package-lock.json file
2. cd into your kafka-lens folder
3. npm install
4. type this in your command line (without quotes) and then press enter: './node_modules/.bin/electron-rebuild'
5. npm start

Let me know if that helps or if you're still getting an error, copy past that error and let me take a look.

**Comment by joncourt** [comment]
Thanks. 

It must be something in my setup because I’ve just been successful in the node docker container after I installed a bunch of gtk3 stuff.

This must get compiled to native somewhere yes?

If I get the docker working smoothly I’ll submit the dockerfile in a PR for others to use if you like.

Thanks for responding so quick.

Jon

**Comment by joncourt** [comment]
Osx. Latest and greatest. Tried centos 7 too. Had some other issues on the way to even getting npm installed and upgraded.

**Comment by howardNa** [comment]
Np jon, hope you get the docker issues sorted out!
